#ifndef INPUTCODES_H
#define INPUTCODES_H

#include <SDL.h>

enum class InputType
{
	ispressed,
	wasPressedThisFrame,
	wasReleasedThisFrame
};

enum class ControllerButton
{
    CB_INVALID = SDL_CONTROLLER_BUTTON_INVALID,
	CB_A = SDL_CONTROLLER_BUTTON_A,
	CB_B = SDL_CONTROLLER_BUTTON_B,
	CB_X = SDL_CONTROLLER_BUTTON_X,
	CB_Y = SDL_CONTROLLER_BUTTON_Y,
    CB_BACK = SDL_CONTROLLER_BUTTON_BACK,
    CB_GUIDE = SDL_CONTROLLER_BUTTON_GUIDE,
    CB_START = SDL_CONTROLLER_BUTTON_START,
    CB_LEFTSTICK = SDL_CONTROLLER_BUTTON_LEFTSTICK,
    CB_RIGHTSTICK = SDL_CONTROLLER_BUTTON_RIGHTSTICK,
    CB_LEFTSHOULDER = SDL_CONTROLLER_BUTTON_LEFTSHOULDER,
    CB_RIGHTSHOULDER = SDL_CONTROLLER_BUTTON_RIGHTSHOULDER,
    CB_DPAD_UP = SDL_CONTROLLER_BUTTON_DPAD_UP,
    CB_DPAD_DOWN = SDL_CONTROLLER_BUTTON_DPAD_DOWN,
    CB_DPAD_LEFT = SDL_CONTROLLER_BUTTON_DPAD_LEFT,
    CB_DPAD_RIGHT = SDL_CONTROLLER_BUTTON_DPAD_RIGHT,
    CB_MISC1 = SDL_CONTROLLER_BUTTON_MISC1, /* Xbox Series X share button, PS5 microphone button, Nintendo Switch Pro capture button, Amazon Luna microphone button */
    CB_PADDLE1 = SDL_CONTROLLER_BUTTON_PADDLE1, /* Xbox Elite paddle P1 (upper left, facing the back) */
    CB_PADDLE2 = SDL_CONTROLLER_BUTTON_PADDLE2, /* Xbox Elite paddle P3 (upper right, facing the back) */
    CB_PADDLE3 = SDL_CONTROLLER_BUTTON_PADDLE3, /* Xbox Elite paddle P2 (lower left, facing the back) */
    CB_PADDLE4 = SDL_CONTROLLER_BUTTON_PADDLE4, /* Xbox Elite paddle P4 (lower right, facing the back) */
    CB_TOUCHPAD = SDL_CONTROLLER_BUTTON_TOUCHPAD, /* PS4/PS5 touchpad button */
    CB_MAX = SDL_CONTROLLER_BUTTON_MAX
};

enum class KeyBoardButton
{
	KB_UNKNOWN = SDL_SCANCODE_UNKNOWN,
	KB_A = SDL_SCANCODE_A,
	KB_B = SDL_SCANCODE_B,
	KB_C = SDL_SCANCODE_C,
	KB_D = SDL_SCANCODE_D,
	KB_E = SDL_SCANCODE_E,
	KB_F = SDL_SCANCODE_F,
	KB_G = SDL_SCANCODE_G,
	KB_H = SDL_SCANCODE_H,
	KB_I = SDL_SCANCODE_I,
	KB_J = SDL_SCANCODE_J,
	KB_K = SDL_SCANCODE_K,
	KB_L = SDL_SCANCODE_L,
	KB_M = SDL_SCANCODE_M,
	KB_N = SDL_SCANCODE_N,
	KB_O = SDL_SCANCODE_O,
	KB_P = SDL_SCANCODE_P,
	KB_Q = SDL_SCANCODE_Q,
	KB_R = SDL_SCANCODE_R,
	KB_S = SDL_SCANCODE_S,
	KB_T = SDL_SCANCODE_T,
	KB_U = SDL_SCANCODE_U,
	KB_V = SDL_SCANCODE_V,
	KB_W = SDL_SCANCODE_W,
	KB_X = SDL_SCANCODE_X,
	KB_Y = SDL_SCANCODE_Y,
	KB_Z = SDL_SCANCODE_Z,
	KB_1 = SDL_SCANCODE_1,
	KB_2 = SDL_SCANCODE_2,
	KB_3 = SDL_SCANCODE_3,
	KB_4 = SDL_SCANCODE_4,
	KB_5 = SDL_SCANCODE_5,
	KB_6 = SDL_SCANCODE_6,
	KB_7 = SDL_SCANCODE_7,
	KB_8 = SDL_SCANCODE_8,
	KB_9 = SDL_SCANCODE_9,
	KB_0 = SDL_SCANCODE_0
};

#endif // !INPUTCODES_H